WebGLUtils=function(){var b=function(a,b){for(var c=["webgl","experimental-webgl","webkit-3d","moz-webgl"],d=null,f=0;f<c.length;++f){try{d=a.getContext(c[f],b)}catch(g){}if(d)break}return d};return{create3DContext:b,setupWebGL:function(a,d,c){function e(a){var b=document.getElementsByTagName("body")[0];if(b){var c=window.WebGLRenderingContext?'It doesn\'t appear your computer can support WebGL.<br/><a href="http://get.webgl.org">Click here for more information.</a>':'This page requires a browser that supports WebGL.<br/><a href="http://get.webgl.org">Click here to upgrade your browser.</a>';
a&&(c+="<br/><br/>Status: "+a);b.innerHTML='<div style="margin: auto; width:500px;z-index:10000;margin-top:20em;text-align:center;">'+c+"</div>"}}c=c||e;a.addEventListener&&a.addEventListener("webglcontextcreationerror",function(a){c(a.statusMessage)},!1);(a=b(a,d))||c("");return a}}}();
window.requestAnimationFrame||(window.requestAnimationFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(b,a){window.setTimeout(b,1E3/60)}}());
window.cancelAnimationFrame||(window.cancelAnimationFrame=window.cancelRequestAnimationFrame||window.webkitCancelAnimationFrame||window.webkitCancelRequestAnimationFrame||window.mozCancelAnimationFrame||window.mozCancelRequestAnimationFrame||window.msCancelAnimationFrame||window.msCancelRequestAnimationFrame||window.oCancelAnimationFrame||window.oCancelRequestAnimationFrame||window.clearTimeout);
WebGLDebugUtils=function(){function b(a){if(null==g){g={};for(var b in a)"number"==typeof a[b]&&(g[a[b]]=b)}}function a(){if(null==g)throw"WebGLDebugUtils.init(ctx) not called";}function d(b){a();var c=g[b];return void 0!==c?c:"*UNKNOWN WebGL ENUM (0x"+b.toString(16)+")"}function c(a,b,c){a=f[a];return void 0!==a&&a[b]?d(c):c.toString()}function e(a){var b=a.getParameter(a.MAX_VERTEX_ATTRIBS),c=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,c);for(var d=0;d<b;++d)a.disableVertexAttribArray(d),a.vertexAttribPointer(d,
4,a.FLOAT,!1,0,0),a.vertexAttrib1f(d,0);a.deleteBuffer(c);b=a.getParameter(a.MAX_TEXTURE_IMAGE_UNITS);for(d=0;d<b;++d)a.activeTexture(a.TEXTURE0+d),a.bindTexture(a.TEXTURE_CUBE_MAP,null),a.bindTexture(a.TEXTURE_2D,null);a.activeTexture(a.TEXTURE0);a.useProgram(null);a.bindBuffer(a.ARRAY_BUFFER,null);a.bindBuffer(a.ELEMENT_ARRAY_BUFFER,null);a.bindFramebuffer(a.FRAMEBUFFER,null);a.bindRenderbuffer(a.RENDERBUFFER,null);a.disable(a.BLEND);a.disable(a.CULL_FACE);a.disable(a.DEPTH_TEST);a.disable(a.DITHER);
a.disable(a.SCISSOR_TEST);a.blendColor(0,0,0,0);a.blendEquation(a.FUNC_ADD);a.blendFunc(a.ONE,a.ZERO);a.clearColor(0,0,0,0);a.clearDepth(1);a.clearStencil(-1);a.colorMask(!0,!0,!0,!0);a.cullFace(a.BACK);a.depthFunc(a.LESS);a.depthMask(!0);a.depthRange(0,1);a.frontFace(a.CCW);a.hint(a.GENERATE_MIPMAP_HINT,a.DONT_CARE);a.lineWidth(1);a.pixelStorei(a.PACK_ALIGNMENT,4);a.pixelStorei(a.UNPACK_ALIGNMENT,4);a.pixelStorei(a.UNPACK_FLIP_Y_WEBGL,!1);a.pixelStorei(a.UNPACK_PREMULTIPLY_ALPHA_WEBGL,!1);a.UNPACK_COLORSPACE_CONVERSION_WEBGL&&
a.pixelStorei(a.UNPACK_COLORSPACE_CONVERSION_WEBGL,a.BROWSER_DEFAULT_WEBGL);a.polygonOffset(0,0);a.sampleCoverage(1,!1);a.scissor(0,0,a.canvas.width,a.canvas.height);a.stencilFunc(a.ALWAYS,0,4294967295);a.stencilMask(4294967295);a.stencilOp(a.KEEP,a.KEEP,a.KEEP);a.viewport(0,0,a.canvas.clientWidth,a.canvas.clientHeight);for(a.clear(a.COLOR_BUFFER_BIT|a.DEPTH_BUFFER_BIT|a.STENCIL_BUFFER_BIT);a.getError(););}var f={enable:{0:!0},disable:{0:!0},getParameter:{0:!0},drawArrays:{0:!0},drawElements:{0:!0,
2:!0},createShader:{0:!0},getShaderParameter:{1:!0},getProgramParameter:{1:!0},getVertexAttrib:{1:!0},vertexAttribPointer:{2:!0},bindTexture:{0:!0},activeTexture:{0:!0},getTexParameter:{0:!0,1:!0},texParameterf:{0:!0,1:!0},texParameteri:{0:!0,1:!0,2:!0},texImage2D:{0:!0,2:!0,6:!0,7:!0},texSubImage2D:{0:!0,6:!0,7:!0},copyTexImage2D:{0:!0,2:!0},copyTexSubImage2D:{0:!0},generateMipmap:{0:!0},bindBuffer:{0:!0},bufferData:{0:!0,2:!0},bufferSubData:{0:!0},getBufferParameter:{0:!0,1:!0},pixelStorei:{0:!0,
1:!0},readPixels:{4:!0,5:!0},bindRenderbuffer:{0:!0},bindFramebuffer:{0:!0},checkFramebufferStatus:{0:!0},framebufferRenderbuffer:{0:!0,1:!0,2:!0},framebufferTexture2D:{0:!0,1:!0,2:!0},getFramebufferAttachmentParameter:{0:!0,1:!0,2:!0},getRenderbufferParameter:{0:!0,1:!0},renderbufferStorage:{0:!0,1:!0},clear:{0:!0},depthFunc:{0:!0},blendFunc:{0:!0,1:!0},blendFuncSeparate:{0:!0,1:!0,2:!0,3:!0},blendEquation:{0:!0},blendEquationSeparate:{0:!0,1:!0},stencilFunc:{0:!0},stencilFuncSeparate:{0:!0,1:!0},
stencilMaskSeparate:{0:!0},stencilOp:{0:!0,1:!0,2:!0},stencilOpSeparate:{0:!0,1:!0,2:!0,3:!0},cullFace:{0:!0},frontFace:{0:!0}},g=null;return{init:b,mightBeEnum:function(b){a();return void 0!==g[b]},glEnumToString:d,glFunctionArgToString:c,makeDebugContext:function(a,e){function f(a,b){return function(){var c=a[b].apply(a,arguments),d=a.getError();0!=d&&(h[d]=!0,e(d,b,arguments));return c}}b(a);e=e||function(a,b,e){for(var f="",h=0;h<e.length;++h)f+=(0==h?"":", ")+c(b,h,e[h]);a="WebGL error "+d(a)+
" in "+b+"("+f+")";window.console&&window.console.log&&window.console.log(a)};var h={},g={},l;for(l in a)g[l]="function"==typeof a[l]?f(a,l):a[l];g.getError=function(){for(var b in h)if(h[b])return h[b]=!1,b;return a.NO_ERROR};return g},makeLostContextSimulatingContext:function(a){function b(){for(var a=Object.keys(t),b=0;b<a.length;++b)delete glErrorShdow_[a]}function c(a,b){var c=a[b];return function(){if(!h){a:{var b=arguments;for(var d=0;d<b.length;++d){var e=b[d];if(e instanceof WebGLBuffer||
e instanceof WebGLFramebuffer||e instanceof WebGLProgram||e instanceof WebGLRenderbuffer||e instanceof WebGLShader||e instanceof WebGLTexture){b=e.__webglDebugContextLostId__==g;break a}}b=!0}if(b)return c.apply(a,arguments);t[a.INVALID_OPERATION]=!0}}}function d(a){return"function"==typeof a?a:function(b){a.handleEvent(b)}}var f={},g=1,h=!1,w=[],x=void 0,v=void 0,y=void 0,t={};for(m in a)f[m]="function"==typeof a[m]?c(a,m):a[m];f.loseContext=function(){if(!h){h=!0;for(++g;a.getError(););b();t[a.CONTEXT_LOST_WEBGL]=
!0;setTimeout(function(){x&&x({statusMessage:"context lost"})},0)}};f.restoreContext=function(){if(h)if(v)setTimeout(function(){for(var b=0;b<w.length;++b){var c=w[b];c instanceof WebGLBuffer?a.deleteBuffer(c):c instanceof WebctxFramebuffer?a.deleteFramebuffer(c):c instanceof WebctxProgram?a.deleteProgram(c):c instanceof WebctxRenderbuffer?a.deleteRenderbuffer(c):c instanceof WebctxShader?a.deleteShader(c):c instanceof WebctxTexture&&a.deleteTexture(c)}e(a);h=!1;v&&(b=v,v=y,y=void 0,b({statusMessage:"context restored"}))},
0);else throw"You can not restore the context without a listener";};f.getError=function(){var b;if(!h)for(;b=a.getError();)t[b]=!0;for(b in t)if(t[b])return delete t[b],b;return a.NO_ERROR};for(var q="createBuffer createFramebuffer createProgram createRenderbuffer createShader createTexture".split(" "),n=0;n<q.length;++n){var m=q[n];f[m]=function(b){return function(){if(h)return null;var c=b.apply(a,arguments);c.__webglDebugContextLostId__=g;w.push(c);return c}}(a[m])}q="getActiveAttrib getActiveUniform getBufferParameter getContextAttributes getAttachedShaders getFramebufferAttachmentParameter getParameter getProgramParameter getProgramInfoLog getRenderbufferParameter getShaderParameter getShaderInfoLog getShaderSource getTexParameter getUniform getUniformLocation getVertexAttrib".split(" ");
for(n=0;n<q.length;++n)m=q[n],f[m]=function(b){return function(){return h?null:b.apply(a,arguments)}}(f[m]);q="isBuffer isEnabled isFramebuffer isProgram isRenderbuffer isShader isTexture".split(" ");for(n=0;n<q.length;++n)m=q[n],f[m]=function(b){return function(){return h?!1:b.apply(a,arguments)}}(f[m]);f.checkFramebufferStatus=function(b){return function(){return h?a.FRAMEBUFFER_UNSUPPORTED:b.apply(a,arguments)}}(f.checkFramebufferStatus);f.getAttribLocation=function(b){return function(){return h?
-1:b.apply(a,arguments)}}(f.getAttribLocation);f.getVertexAttribOffset=function(b){return function(){return h?0:b.apply(a,arguments)}}(f.getVertexAttribOffset);f.isContextLost=function(){return h};f.registerOnContextLostListener=function(a){x=d(a)};f.registerOnContextRestoredListener=function(a){h?y=d(a):v=d(a)};return f},resetToInitialState:e}}();function initShaders(b,a,d){a=createProgram(b,a,d);if(!a)return console.log("Failed to create program"),!1;b.useProgram(a);b.program=a;return!0}
function createProgram(b,a,d){a=loadShader(b,b.VERTEX_SHADER,a);d=loadShader(b,b.FRAGMENT_SHADER,d);if(!a||!d)return null;var c=b.createProgram();if(!c)return null;b.attachShader(c,a);b.attachShader(c,d);b.linkProgram(c);if(!b.getProgramParameter(c,b.LINK_STATUS)){var e=b.getProgramInfoLog(c);console.log("Failed to link program: "+e);b.deleteProgram(c);b.deleteShader(d);b.deleteShader(a);return null}return c}
function loadShader(b,a,d){a=b.createShader(a);if(null==a)return console.log("unable to create shader"),null;b.shaderSource(a,d);b.compileShader(a);return b.getShaderParameter(a,b.COMPILE_STATUS)?a:(d=b.getShaderInfoLog(a),console.log("Failed to compile shader: "+d),b.deleteShader(a),null)}function getWebGLContext(b,a){var d=WebGLUtils.setupWebGL(b);if(!d)return null;if(2>arguments.length||a)d=WebGLDebugUtils.makeDebugContext(d);return d}
var Matrix4=function(b){if(b&&"object"===typeof b&&b.hasOwnProperty("elements")){var a=b.elements,d=new Float32Array(16);for(b=0;16>b;++b)d[b]=a[b];this.elements=d}else this.elements=new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1])};Matrix4.prototype.setIdentity=function(){var b=this.elements;b[0]=1;b[4]=0;b[8]=0;b[12]=0;b[1]=0;b[5]=1;b[9]=0;b[13]=0;b[2]=0;b[6]=0;b[10]=1;b[14]=0;b[3]=0;b[7]=0;b[11]=0;b[15]=1;return this};
Matrix4.prototype.set=function(b){var a=b.elements,d=this.elements;if(a!==d){for(b=0;16>b;++b)d[b]=a[b];return this}};Matrix4.prototype.concat=function(b){var a,d=a=this.elements,c=b.elements;if(a===c)for(c=new Float32Array(16),b=0;16>b;++b)c[b]=a[b];for(b=0;4>b;b++){var e=d[b],f=d[b+4],g=d[b+8],h=d[b+12];a[b]=e*c[0]+f*c[1]+g*c[2]+h*c[3];a[b+4]=e*c[4]+f*c[5]+g*c[6]+h*c[7];a[b+8]=e*c[8]+f*c[9]+g*c[10]+h*c[11];a[b+12]=e*c[12]+f*c[13]+g*c[14]+h*c[15]}return this};Matrix4.prototype.multiply=Matrix4.prototype.concat;
Matrix4.prototype.multiplyVector3=function(b){var a=this.elements;b=b.elements;var d=new Vector3,c=d.elements;c[0]=b[0]*a[0]+b[1]*a[4]+b[2]*a[8]+a[12];c[1]=b[0]*a[1]+b[1]*a[5]+b[2]*a[9]+a[13];c[2]=b[0]*a[2]+b[1]*a[6]+b[2]*a[10]+a[14];return d};
Matrix4.prototype.multiplyVector4=function(b){var a=this.elements;b=b.elements;var d=new Vector4,c=d.elements;c[0]=b[0]*a[0]+b[1]*a[4]+b[2]*a[8]+b[3]*a[12];c[1]=b[0]*a[1]+b[1]*a[5]+b[2]*a[9]+b[3]*a[13];c[2]=b[0]*a[2]+b[1]*a[6]+b[2]*a[10]+b[3]*a[14];c[3]=b[0]*a[3]+b[1]*a[7]+b[2]*a[11]+b[3]*a[15];return d};
Matrix4.prototype.transpose=function(){var b=this.elements,a=b[1];b[1]=b[4];b[4]=a;a=b[2];b[2]=b[8];b[8]=a;a=b[3];b[3]=b[12];b[12]=a;a=b[6];b[6]=b[9];b[9]=a;a=b[7];b[7]=b[13];b[13]=a;a=b[11];b[11]=b[14];b[14]=a;return this};
Matrix4.prototype.setInverseOf=function(b){var a=b.elements;b=this.elements;var d=new Float32Array(16);d[0]=a[5]*a[10]*a[15]-a[5]*a[11]*a[14]-a[9]*a[6]*a[15]+a[9]*a[7]*a[14]+a[13]*a[6]*a[11]-a[13]*a[7]*a[10];d[4]=-a[4]*a[10]*a[15]+a[4]*a[11]*a[14]+a[8]*a[6]*a[15]-a[8]*a[7]*a[14]-a[12]*a[6]*a[11]+a[12]*a[7]*a[10];d[8]=a[4]*a[9]*a[15]-a[4]*a[11]*a[13]-a[8]*a[5]*a[15]+a[8]*a[7]*a[13]+a[12]*a[5]*a[11]-a[12]*a[7]*a[9];d[12]=-a[4]*a[9]*a[14]+a[4]*a[10]*a[13]+a[8]*a[5]*a[14]-a[8]*a[6]*a[13]-a[12]*a[5]*a[10]+
a[12]*a[6]*a[9];d[1]=-a[1]*a[10]*a[15]+a[1]*a[11]*a[14]+a[9]*a[2]*a[15]-a[9]*a[3]*a[14]-a[13]*a[2]*a[11]+a[13]*a[3]*a[10];d[5]=a[0]*a[10]*a[15]-a[0]*a[11]*a[14]-a[8]*a[2]*a[15]+a[8]*a[3]*a[14]+a[12]*a[2]*a[11]-a[12]*a[3]*a[10];d[9]=-a[0]*a[9]*a[15]+a[0]*a[11]*a[13]+a[8]*a[1]*a[15]-a[8]*a[3]*a[13]-a[12]*a[1]*a[11]+a[12]*a[3]*a[9];d[13]=a[0]*a[9]*a[14]-a[0]*a[10]*a[13]-a[8]*a[1]*a[14]+a[8]*a[2]*a[13]+a[12]*a[1]*a[10]-a[12]*a[2]*a[9];d[2]=a[1]*a[6]*a[15]-a[1]*a[7]*a[14]-a[5]*a[2]*a[15]+a[5]*a[3]*a[14]+
a[13]*a[2]*a[7]-a[13]*a[3]*a[6];d[6]=-a[0]*a[6]*a[15]+a[0]*a[7]*a[14]+a[4]*a[2]*a[15]-a[4]*a[3]*a[14]-a[12]*a[2]*a[7]+a[12]*a[3]*a[6];d[10]=a[0]*a[5]*a[15]-a[0]*a[7]*a[13]-a[4]*a[1]*a[15]+a[4]*a[3]*a[13]+a[12]*a[1]*a[7]-a[12]*a[3]*a[5];d[14]=-a[0]*a[5]*a[14]+a[0]*a[6]*a[13]+a[4]*a[1]*a[14]-a[4]*a[2]*a[13]-a[12]*a[1]*a[6]+a[12]*a[2]*a[5];d[3]=-a[1]*a[6]*a[11]+a[1]*a[7]*a[10]+a[5]*a[2]*a[11]-a[5]*a[3]*a[10]-a[9]*a[2]*a[7]+a[9]*a[3]*a[6];d[7]=a[0]*a[6]*a[11]-a[0]*a[7]*a[10]-a[4]*a[2]*a[11]+a[4]*a[3]*
a[10]+a[8]*a[2]*a[7]-a[8]*a[3]*a[6];d[11]=-a[0]*a[5]*a[11]+a[0]*a[7]*a[9]+a[4]*a[1]*a[11]-a[4]*a[3]*a[9]-a[8]*a[1]*a[7]+a[8]*a[3]*a[5];d[15]=a[0]*a[5]*a[10]-a[0]*a[6]*a[9]-a[4]*a[1]*a[10]+a[4]*a[2]*a[9]+a[8]*a[1]*a[6]-a[8]*a[2]*a[5];var c=a[0]*d[0]+a[1]*d[4]+a[2]*d[8]+a[3]*d[12];if(0===c)return this;c=1/c;for(a=0;16>a;a++)b[a]=d[a]*c;return this};Matrix4.prototype.invert=function(){return this.setInverseOf(this)};
Matrix4.prototype.setOrtho=function(b,a,d,c,e,f){if(b===a||d===c||e===f)throw"null frustum";var g=1/(a-b),h=1/(c-d),l=1/(f-e),k=this.elements;k[0]=2*g;k[1]=0;k[2]=0;k[3]=0;k[4]=0;k[5]=2*h;k[6]=0;k[7]=0;k[8]=0;k[9]=0;k[10]=-2*l;k[11]=0;k[12]=-(a+b)*g;k[13]=-(c+d)*h;k[14]=-(f+e)*l;k[15]=1;return this};Matrix4.prototype.ortho=function(b,a,d,c,e,f){return this.concat((new Matrix4).setOrtho(b,a,d,c,e,f))};
Matrix4.prototype.setFrustum=function(b,a,d,c,e,f){if(b===a||c===d||e===f)throw"null frustum";if(0>=e)throw"near <= 0";if(0>=f)throw"far <= 0";var g=1/(a-b),h=1/(c-d),l=1/(f-e),k=this.elements;k[0]=2*e*g;k[1]=0;k[2]=0;k[3]=0;k[4]=0;k[5]=2*e*h;k[6]=0;k[7]=0;k[8]=(a+b)*g;k[9]=(c+d)*h;k[10]=-(f+e)*l;k[11]=-1;k[12]=0;k[13]=0;k[14]=-2*e*f*l;k[15]=0;return this};Matrix4.prototype.frustum=function(b,a,d,c,e,f){return this.concat((new Matrix4).setFrustum(b,a,d,c,e,f))};
Matrix4.prototype.setPerspective=function(b,a,d,c){if(d===c||0===a)throw"null frustum";if(0>=d)throw"near <= 0";if(0>=c)throw"far <= 0";b=Math.PI*b/180/2;var e=Math.sin(b);if(0===e)throw"null frustum";var f=1/(c-d);e=Math.cos(b)/e;b=this.elements;b[0]=e/a;b[1]=0;b[2]=0;b[3]=0;b[4]=0;b[5]=e;b[6]=0;b[7]=0;b[8]=0;b[9]=0;b[10]=-(c+d)*f;b[11]=-1;b[12]=0;b[13]=0;b[14]=-2*d*c*f;b[15]=0;return this};Matrix4.prototype.perspective=function(b,a,d,c){return this.concat((new Matrix4).setPerspective(b,a,d,c))};
Matrix4.prototype.setScale=function(b,a,d){var c=this.elements;c[0]=b;c[4]=0;c[8]=0;c[12]=0;c[1]=0;c[5]=a;c[9]=0;c[13]=0;c[2]=0;c[6]=0;c[10]=d;c[14]=0;c[3]=0;c[7]=0;c[11]=0;c[15]=1;return this};Matrix4.prototype.scale=function(b,a,d){var c=this.elements;c[0]*=b;c[4]*=a;c[8]*=d;c[1]*=b;c[5]*=a;c[9]*=d;c[2]*=b;c[6]*=a;c[10]*=d;c[3]*=b;c[7]*=a;c[11]*=d;return this};
Matrix4.prototype.setTranslate=function(b,a,d){var c=this.elements;c[0]=1;c[4]=0;c[8]=0;c[12]=b;c[1]=0;c[5]=1;c[9]=0;c[13]=a;c[2]=0;c[6]=0;c[10]=1;c[14]=d;c[3]=0;c[7]=0;c[11]=0;c[15]=1;return this};Matrix4.prototype.translate=function(b,a,d){var c=this.elements;c[12]+=c[0]*b+c[4]*a+c[8]*d;c[13]+=c[1]*b+c[5]*a+c[9]*d;c[14]+=c[2]*b+c[6]*a+c[10]*d;c[15]+=c[3]*b+c[7]*a+c[11]*d;return this};
Matrix4.prototype.setRotate=function(b,a,d,c){b=Math.PI*b/180;var e=this.elements,f=Math.sin(b);b=Math.cos(b);if(0!==a&&0===d&&0===c)0>a&&(f=-f),e[0]=1,e[4]=0,e[8]=0,e[12]=0,e[1]=0,e[5]=b,e[9]=-f,e[13]=0,e[2]=0,e[6]=f,e[10]=b,e[14]=0,e[3]=0,e[7]=0,e[11]=0;else if(0===a&&0!==d&&0===c)0>d&&(f=-f),e[0]=b,e[4]=0,e[8]=f,e[12]=0,e[1]=0,e[5]=1,e[9]=0,e[13]=0,e[2]=-f,e[6]=0,e[10]=b,e[14]=0,e[3]=0,e[7]=0,e[11]=0;else if(0===a&&0===d&&0!==c)0>c&&(f=-f),e[0]=b,e[4]=-f,e[8]=0,e[12]=0,e[1]=f,e[5]=b,e[9]=0,e[13]=
0,e[2]=0,e[6]=0,e[10]=1,e[14]=0,e[3]=0,e[7]=0,e[11]=0;else{var g=Math.sqrt(a*a+d*d+c*c);1!==g&&(g=1/g,a*=g,d*=g,c*=g);g=1-b;var h=a*d,l=d*c,k=c*a,u=a*f,r=d*f;f*=c;e[0]=a*a*g+b;e[1]=h*g+f;e[2]=k*g-r;e[3]=0;e[4]=h*g-f;e[5]=d*d*g+b;e[6]=l*g+u;e[7]=0;e[8]=k*g+r;e[9]=l*g-u;e[10]=c*c*g+b;e[11]=0;e[12]=0;e[13]=0;e[14]=0}e[15]=1;return this};Matrix4.prototype.rotate=function(b,a,d,c){return this.concat((new Matrix4).setRotate(b,a,d,c))};
Matrix4.prototype.setLookAt=function(b,a,d,c,e,f,g,h,l){c-=b;e-=a;f-=d;var k=1/Math.sqrt(c*c+e*e+f*f);c*=k;e*=k;f*=k;k=e*l-f*h;l=f*g-c*l;g=c*h-e*g;h=1/Math.sqrt(k*k+l*l+g*g);k*=h;l*=h;g*=h;h=this.elements;h[0]=k;h[1]=l*f-g*e;h[2]=-c;h[3]=0;h[4]=l;h[5]=g*c-k*f;h[6]=-e;h[7]=0;h[8]=g;h[9]=k*e-l*c;h[10]=-f;h[11]=0;h[12]=0;h[13]=0;h[14]=0;h[15]=1;return this.translate(-b,-a,-d)};Matrix4.prototype.lookAt=function(b,a,d,c,e,f,g,h,l){return this.concat((new Matrix4).setLookAt(b,a,d,c,e,f,g,h,l))};
Matrix4.prototype.dropShadow=function(b,a){var d=new Matrix4,c=d.elements,e=b[0]*a[0]+b[1]*a[1]+b[2]*a[2]+b[3]*a[3];c[0]=e-a[0]*b[0];c[1]=-a[1]*b[0];c[2]=-a[2]*b[0];c[3]=-a[3]*b[0];c[4]=-a[0]*b[1];c[5]=e-a[1]*b[1];c[6]=-a[2]*b[1];c[7]=-a[3]*b[1];c[8]=-a[0]*b[2];c[9]=-a[1]*b[2];c[10]=e-a[2]*b[2];c[11]=-a[3]*b[2];c[12]=-a[0]*b[3];c[13]=-a[1]*b[3];c[14]=-a[2]*b[3];c[15]=e-a[3]*b[3];return this.concat(d)};
Matrix4.prototype.dropShadowDirectionally=function(b,a,d,c,e,f,g,h,l){return this.dropShadow([b,a,d,-(c*b+e*a+f*d)],[g,h,l,0])};var Vector3=function(b){var a=new Float32Array(3);b&&"object"===typeof b&&(a[0]=b[0],a[1]=b[1],a[2]=b[2]);this.elements=a};Vector3.prototype.normalize=function(){var b=this.elements,a=b[0],d=b[1],c=b[2],e=Math.sqrt(a*a+d*d+c*c);if(e){if(1==e)return this}else return b[0]=0,b[1]=0,b[2]=0,this;e=1/e;b[0]=a*e;b[1]=d*e;b[2]=c*e;return this};
var Vector4=function(b){var a=new Float32Array(4);b&&"object"===typeof b&&(a[0]=b[0],a[1]=b[1],a[2]=b[2],a[3]=b[3]);this.elements=a},VSHADER_SOURCE="attribute vec4 a_Position;\nattribute vec4 a_Color;\nattribute vec4 a_Normal;\nuniform mat4 u_MvpMatrix;\nuniform mat4 u_NormalMatrix;\nvarying vec4 v_Color;\nvoid main() {\n  vec3 lightDirection = vec3(0.35, 0.84, -0.57);\n  gl_Position = u_MvpMatrix * a_Position;\n  vec3 normal = normalize(vec3(u_NormalMatrix * a_Normal));\n  float nDotL = max(dot(normal, lightDirection), 0.0);\n  v_Color = vec4(a_Color.rgb * nDotL, a_Color.a);\n}\n",
FSHADER_SOURCE="#ifdef GL_ES\nprecision mediump float;\n#endif\nvarying vec4 v_Color;\nvoid main() {\n  gl_FragColor = v_Color;\n}\n";
function main(){var b=document.getElementById("webgl"),a=getWebGLContext(b);if(a)if(initShaders(a,VSHADER_SOURCE,FSHADER_SOURCE)){a.clearColor(.1,.1,.1,0);a.enable(a.DEPTH_TEST);var d=a.program;d.a_Position=a.getAttribLocation(d,"a_Position");d.a_Normal=a.getAttribLocation(d,"a_Normal");d.a_Color=a.getAttribLocation(d,"a_Color");d.u_MvpMatrix=a.getUniformLocation(d,"u_MvpMatrix");d.u_NormalMatrix=a.getUniformLocation(d,"u_NormalMatrix");if(0>d.a_Position||0>d.a_Normal||0>d.a_Color||!d.u_MvpMatrix||
!d.u_NormalMatrix)console.log("attribute, uniform");else{var c=initVertexBuffers(a,d);if(c){var e=new Matrix4;e.setPerspective(30,b.width/b.height,1,5E3);e.lookAt(0,500,200,0,0,0,0,1,0);readOBJFile("wolf03.obj",a,c,7,!0);var f=[15,20];initEventHandlers(b,f);var g=function(){draw(a,a.program,f,e,c);requestAnimationFrame(g,b)};g()}else console.log("Failed to set the vertex information")}}else console.log("Failed to intialize shaders.");else console.log("Failed to get the rendering context for WebGL")}
function initVertexBuffers(b,a){var d={};d.vertexBuffer=createEmptyArrayBuffer(b,a.a_Position,3,b.FLOAT);d.normalBuffer=createEmptyArrayBuffer(b,a.a_Normal,3,b.FLOAT);d.colorBuffer=createEmptyArrayBuffer(b,a.a_Color,4,b.FLOAT);d.indexBuffer=b.createBuffer();if(!(d.vertexBuffer&&d.normalBuffer&&d.colorBuffer&&d.indexBuffer))return null;b.bindBuffer(b.ARRAY_BUFFER,null);return d}
function createEmptyArrayBuffer(b,a,d,c){var e=b.createBuffer();if(!e)return console.log("Failed to create the buffer object"),null;b.bindBuffer(b.ARRAY_BUFFER,e);b.vertexAttribPointer(a,d,c,!1,0,0);b.enableVertexAttribArray(a);return e}function readOBJFile(b,a,d,c,e){var f=new XMLHttpRequest;f.onreadystatechange=function(){4===f.readyState&&404!==f.status&&onReadOBJFile(f.responseText,b,a,d,c,e)};f.open("GET",b,!0);f.send()}var g_objDoc=null,g_drawingInfo=null;
function onReadOBJFile(b,a,d,c,e,f){a=new OBJDoc(a);a.parse(b,e,f)?g_objDoc=a:(g_drawingInfo=g_objDoc=null,console.log("OBJ file parsing error."))}var g_modelMatrix=new Matrix4,g_mvpMatrix=new Matrix4,g_normalMatrix=new Matrix4;
function draw(b,a,d,c,e){null!=g_objDoc&&g_objDoc.isMTLComplete()&&(g_drawingInfo=onReadComplete(b,e,g_objDoc),g_objDoc=null);g_drawingInfo&&(b.clear(b.COLOR_BUFFER_BIT|b.DEPTH_BUFFER_BIT),g_modelMatrix.setRotate(d[0],1,0,0),g_modelMatrix.rotate(-d[1],0,0,1),g_normalMatrix.setInverseOf(g_modelMatrix),g_normalMatrix.transpose(),b.uniformMatrix4fv(a.u_NormalMatrix,!1,g_normalMatrix.elements),g_mvpMatrix.set(c),g_mvpMatrix.multiply(g_modelMatrix),b.uniformMatrix4fv(a.u_MvpMatrix,!1,g_mvpMatrix.elements),
b.drawElements(b.TRIANGLES,g_drawingInfo.indices.length,b.UNSIGNED_SHORT,0))}
function onReadComplete(b,a,d){d=d.getDrawingInfo();b.bindBuffer(b.ARRAY_BUFFER,a.vertexBuffer);b.bufferData(b.ARRAY_BUFFER,d.vertices,b.STATIC_DRAW);b.bindBuffer(b.ARRAY_BUFFER,a.normalBuffer);b.bufferData(b.ARRAY_BUFFER,d.normals,b.STATIC_DRAW);b.bindBuffer(b.ARRAY_BUFFER,a.colorBuffer);b.bufferData(b.ARRAY_BUFFER,d.colors,b.STATIC_DRAW);b.bindBuffer(b.ELEMENT_ARRAY_BUFFER,a.indexBuffer);b.bufferData(b.ELEMENT_ARRAY_BUFFER,d.indices,b.STATIC_DRAW);return d}
var OBJDoc=function(b){this.fileName=b;this.mtls=[];this.objects=[];this.vertices=[];this.normals=[]};
OBJDoc.prototype.parse=function(b,a,d){b=clearEnds(b).split("\n");b.push(null);for(var c=0,e=null,f="",g,h=new StringParser;null!=(g=b[c++]);)if(h.init(g),g=h.getWord(),null!=g)switch(g){case "#":continue;case "mtllib":g=this.parseMtllib(h,this.fileName);var l=new MTLDoc;this.mtls.push(l);var k=new XMLHttpRequest;k.onreadystatechange=function(){4==k.readyState&&(404!=k.status?onReadMTLFile(k.responseText,l):l.complete=!0)};k.open("GET",g,!0);k.send();continue;case "o":case "g":e=this.parseObjectName(h);
this.objects.push(e);continue;case "v":g=this.parseVertex(h,a);this.vertices.push(g);continue;case "vn":g=this.parseNormal(h);this.normals.push(g);continue;case "usemtl":f=this.parseUsemtl(h);continue;case "f":g=this.parseFace(h,f,this.vertices,d),e.addFace(g)}return!0};OBJDoc.prototype.parseMtllib=function(b,a){var d=a.lastIndexOf("/"),c="";0<d&&(c=a.substr(0,d+1));return c+b.getWord()};OBJDoc.prototype.parseObjectName=function(b){b=b.getWord();return new OBJObject(b)};
OBJDoc.prototype.parseVertex=function(b,a){var d=b.getFloat()*a,c=b.getFloat()*a,e=b.getFloat()*a;return new Vertex(d,c,e)};OBJDoc.prototype.parseNormal=function(b){var a=b.getFloat(),d=b.getFloat();b=b.getFloat();return new Normal(a,d,b)};OBJDoc.prototype.parseUsemtl=function(b){return b.getWord()};
OBJDoc.prototype.parseFace=function(b,a,d,c){for(a=new Face(a);;){var e=b.getWord();if(null==e)break;e=e.split("/");if(1<=e.length){var f=parseInt(e[0])-1;a.vIndices.push(f)}3<=e.length?(e=parseInt(e[2])-1,a.nIndices.push(e)):a.nIndices.push(-1)}b=[d[a.vIndices[1]].x,d[a.vIndices[1]].y,d[a.vIndices[1]].z];e=[d[a.vIndices[2]].x,d[a.vIndices[2]].y,d[a.vIndices[2]].z];f=calcNormal([d[a.vIndices[0]].x,d[a.vIndices[0]].y,d[a.vIndices[0]].z],b,e);null==f&&(4<=a.vIndices.length&&(f=calcNormal(b,e,[d[a.vIndices[3]].x,
d[a.vIndices[3]].y,d[a.vIndices[3]].z])),null==f&&(f=[0,1,0]));c&&(f[0]=-f[0],f[1]=-f[1],f[2]=-f[2]);a.normal=new Normal(f[0],f[1],f[2]);if(3<a.vIndices.length){d=a.vIndices.length-2;c=Array(3*d);b=Array(3*d);for(e=0;e<d;e++)c[3*e+0]=a.vIndices[0],c[3*e+1]=a.vIndices[e+1],c[3*e+2]=a.vIndices[e+2],b[3*e+0]=a.nIndices[0],b[3*e+1]=a.nIndices[e+1],b[3*e+2]=a.nIndices[e+2];a.vIndices=c;a.nIndices=b}a.numIndices=a.vIndices.length;return a};
function onReadMTLFile(b,a){var d=clearEnds(b).split("\n");d.push(null);for(var c=0,e,f="",g=new StringParser;null!=(e=d[c++]);)if(g.init(e),e=g.getWord(),null!=e)switch(e){case "#":continue;case "newmtl":f=a.parseNewmtl(g);continue;case "Kd":""!=f&&(f=a.parseRGB(g,f),a.materials.push(f),f="")}a.complete=!0}OBJDoc.prototype.isMTLComplete=function(){if(0==this.mtls.length)return!0;for(var b=0;b<this.mtls.length;b++)if(!this.mtls[b].complete)return!1;return!0};
OBJDoc.prototype.findColor=function(b){for(var a=0;a<this.mtls.length;a++)for(var d=0;d<this.mtls[a].materials.length;d++)if(trim(this.mtls[a].materials[d].name)==trim(b))return this.mtls[a].materials[d].color;return new Color(.8,.8,.8,1)};
OBJDoc.prototype.getDrawingInfo=function(){for(var b=0,a=0;a<this.objects.length;a++)b+=this.objects[a].numIndices;a=b;var d=new Float32Array(3*a),c=new Float32Array(3*a),e=new Float32Array(4*a);b=new Uint16Array(b);var f=0;for(a=0;a<this.objects.length;a++)for(var g=this.objects[a],h=0;h<g.faces.length;h++)for(var l=g.faces[h],k=this.findColor(l.materialName),u=l.normal,r=0;r<l.vIndices.length;r++){b[f]=f;var p=this.vertices[l.vIndices[r]];d[3*f+0]=p.x;d[3*f+1]=p.y;d[3*f+2]=p.z;e[4*f+0]=k.r;e[4*
f+1]=k.g;e[4*f+2]=k.b;e[4*f+3]=k.a;p=l.nIndices[r];0<=p?(p=this.normals[p],c[3*f+0]=p.x,c[3*f+1]=p.y,c[3*f+2]=p.z):(c[3*f+0]=u.x,c[3*f+1]=u.y,c[3*f+2]=u.z);f++}return new DrawingInfo(d,c,e,b)};var MTLDoc=function(){this.complete=!1;this.materials=[]};MTLDoc.prototype.parseNewmtl=function(b){return b.getWord()};MTLDoc.prototype.parseRGB=function(b,a){var d=b.getFloat(),c=b.getFloat(),e=b.getFloat();return new Material(a,d,c,e,1)};
var Material=function(b,a,d,c,e){this.name=b;this.color=new Color(a,d,c,e)},Vertex=function(b,a,d){this.x=b;this.y=a;this.z=d},Normal=function(b,a,d){this.x=b;this.y=a;this.z=d},Color=function(b,a,d,c){this.r=b;this.g=a;this.b=d;this.a=c},OBJObject=function(b){this.name=b;this.faces=[];this.numIndices=0};OBJObject.prototype.addFace=function(b){this.faces.push(b);this.numIndices+=b.numIndices};
var Face=function(b){this.materialName=b;null==b&&(this.materialName="");this.vIndices=[];this.nIndices=[]},DrawingInfo=function(b,a,d,c){this.vertices=b;this.normals=a;this.colors=d;this.indices=c},StringParser=function(b){this.str;this.index;this.init(b)};StringParser.prototype.init=function(b){this.str=b;this.index=0};
StringParser.prototype.skipDelimiters=function(){for(var b=this.index,a=this.str.length;b<a;b++){var d=this.str.charAt(b);if("\t"!=d&&" "!=d&&"("!=d&&")"!=d&&'"'!=d)break}this.index=b};StringParser.prototype.skipToNextWord=function(){this.skipDelimiters();var b=getWordLength(this.str,this.index);this.index+=b+1};StringParser.prototype.getWord=function(){this.skipDelimiters();var b=getWordLength(this.str,this.index);if(0==b)return null;var a=this.str.substr(this.index,b);this.index+=b+1;return a};
StringParser.prototype.getInt=function(){return parseInt(this.getWord())};StringParser.prototype.getFloat=function(){return parseFloat(this.getWord())};function getWordLength(b,a){for(var d=a,c=b.length;d<c;d++){var e=b.charAt(d);if("\t"==e||" "==e||"("==e||")"==e||'"'==e)break}return d-a}
function initEventHandlers(b,a){var d=-1,c=-1;b.ontouchmove=b.onmousemove=function(e){e.preventDefault();var f=e.clientX;e=e.clientY;var g=300/b.height,h=g*(f-d);a[0]=Math.max(Math.min(a[0]+g*(e-c),90),-90);45<a[0]&&(a[0]=45);-45>a[0]&&(a[0]=-45);a[1]+=h;45<a[1]&&(a[1]=45);-45>a[1]&&(a[1]=-45);d=f;c=e}}
function calcNormal(b,a,d){for(var c=new Float32Array(3),e=new Float32Array(3),f=0;3>f;f++)c[f]=b[f]-a[f],e[f]=d[f]-a[f];b=new Float32Array(3);b[0]=c[1]*e[2]-c[2]*e[1];b[1]=c[2]*e[0]-c[0]*e[2];b[2]=c[0]*e[1]-c[1]*e[0];c=new Vector3(b);c.normalize();return c.elements}function trim(b){return b.replace(/^\s+/,"").replace(/\s+$/,"")}function clearEnds(b){return b.replace(/\r\n|\r/gi,"\n")};
